Repository tsukuba-shinkan/shinkan-web, pull requests merged in 2020-03, with the labels that each got.

#5 [Chore] Contribution Guideの追加
  CONTRIBUTING.md
  README.md
Labels: documentation

#7 [Chore] Linter設定を更新
  .eslintignore
  .eslintrc.js
  .github/workflows/push.yml
  .prettierrc
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/components/header.js
  src/components/layout.js
Labels: enhancement

#13 データソースからの取り込みを追加（#8）
  .template.env
  README.md
  gatsby-config.js
  package-lock.json
  package.json
  plugins/gatsby-source-shinkan-web/README.md
  plugins/gatsby-source-shinkan-web/gatsby-node.js
  plugins/gatsby-source-shinkan-web/package-lock.json
  plugins/gatsby-source-shinkan-web/package.json
Labels: data-reading

#22 データフローのドキュメントを追加
  DATAFLOW.md
  README.md
Labels: documentation

#21 Contribution Guideの更新、画像がずれる問題の修正
  CONTRIBUTING.md
  README.md
  src/styles/global.css
Labels: documentation

#26 紹介文の自動マークアップを実装（#23）
  src/templates/PostTemplate.js
Labels: UI, data-reading

#25 [Add] トップページ画像から個別ページへのリンク
  src/pages/index.js
Labels: UI

#33 fix: 不適切なリンクの記述
  src/components/layout.js
Labels: bug

#37 PRの提出要件を明確化
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#41 fix: 開発ビルドのコマンドを修正
  README.md
Labels: enhancement

#47 Revert "[Update] issue templates"
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug

#43 SASS/SCSSビルド環境の整備
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/layout.js
  src/components/layout.scss
  src/styles/global.css
  src/styles/global.scss
Labels: enhancement

#45 Stylelintの導入
  .stylelintrc.js
  package-lock.json
  package.json
  src/components/layout.scss
  src/styles/global.scss
Labels: enhancement

#49 パッケージ情報の修正
  package-lock.json
  package.json
Labels: documentation

#50 αリリース前のドキュメント記述削除
  CONTRIBUTING.md
Labels: documentation
