Repository tsukuba-shinkan/shinkan-web, pull requests merged in 2020-04, with the labels that each got.

#66 [Update] アイコンの変更
  gatsby-config.js
  src/images/shinkan-web-icon-transparent.png
Labels: UI

#69 [Fix] floatをflexboxに置き換え
  src/styles/global.scss
Labels: UI

#74 [Add]revise footer
  src/components/layout.js
Labels: UI, enhancement

#73 トップページUIの再実装
  .stylelintrc.js
  src/pages/index.js
  src/pages/index.scss
  src/styles/global.scss
  src/styles/media.scss
  src/styles/vars.scss
Labels: UI, enhancement

#81 [Fix] Headerのh1を削除
  src/components/header.js
  src/styles/global.scss
Labels: enhancement

#82 poster:hover表示によりFooterのリンクが押せない問題の修正
  src/styles/global.scss
Labels: bug

#64 [Add] gatsby-images導入
  gatsby-config.js
  package-lock.json
  package.json
  plugins/gatsby-source-shinkan-web/gatsby-node.js
  src/components/Fixed180,js
  src/components/Fixed200.js
  src/components/Fluid700.js
  src/components/Img.js
  src/components/image.js
  src/pages/index.js
  src/styles/global.scss
  src/templates/PostTemplate.js
Labels: enhancement, help wanted

#75 Lintルールのアップデート
  .eslintrc.js
  package-lock.json
  package.json
  plugins/gatsby-source-shinkan-web/gatsby-node.js
  src/components/Fixed180,js
  src/components/Fixed200.js
  src/components/Fluid700.js
  src/components/Img.js
  src/components/header.js
  src/pages/index.js
  src/templates/PostTemplate.js
Labels: enhancement

#87 画像alt属性の欠損を補完
  src/components/Fixed180,js
  src/components/Fixed200.js
  src/components/Fluid700.js
  src/components/Img.js
  src/components/image.js
  src/components/logo.js
  src/pages/index.js
  src/templates/PostTemplate.js
Labels: bug

#88 [Update] ロゴ読み込みの修正、それに伴うデザイン調整
  src/components/header.js
  src/components/layout.js
  src/components/schoollogo.js
  src/components/shinkanweblogo.js
  src/styles/global.scss
Labels: enhancement

#94 [Fix] ポスター画像の表示崩れを修正
  src/components/Fluid200.js
  src/pages/index.js
  src/pages/index.scss
Labels: UI, bug

#93 個別ページUIの実装
  package-lock.json
  package.json
  src/components/header.js
  src/components/layout.js
  src/pages/index.js
  src/styles/global.scss
  src/styles/vars.scss
  src/templates/PostTemplate.js
  src/templates/PostTemplate.scss
Labels: UI, enhancement

#102 [Update] aboutページのスタイリング fix #101
  src/pages/about.js
  src/pages/about.scss
Labels: enhancement

#111 [Add] Google Analytics の追加
  gatsby-config.js
  package-lock.json
  package.json
  src/pages/about.js
Labels: enhancement

#110 [Delete] 不要なgatsby-image コンポーネントの削除
  src/components/Fixed180.js
  src/components/Fixed200.js
Labels: enhancement

#121 [Fix] og:descriptionを設定
  src/pages/about.js
  src/pages/index.js
  src/templates/PostTemplate.js
Labels: enhancement

#123 スマホでのトップページ横方向のあふれを修正
  src/pages/index.scss
Labels: bug

#128 フィルタ表示機能を追加
  src/lib/normalize.js
  src/pages/index.js
  src/pages/index.scss
Labels: UI, enhancement

#100 [Add] ポスターの順番をランダム化
  src/pages/index.js
Labels: UI, enhancement

#129 [Fix] デプロイの問題の修正
  .github/workflows/push.yml
  gatsby-config.js
Labels: bug

#132 Revert "[Chore] build時にGatsbyのキャッシュを利用するように変更"
  .github/workflows/push.yml
Labels: bug

#134 [Fix] デプロイの修正
  .github/workflows/push.yml
Labels: bug

#133 [Chore] ビルド時にGatsbyのキャッシュを利用するように変更（修正版）
  .github/workflows/push.yml
Labels: bug

#135 [Add] lazy load component
  package-lock.json
  package.json
  src/components/OrgListItem.js
  src/pages/index.js
Labels: enhancement

#137 [Internal][Chore] デプロイCIのエラー修正
  .github/workflows/push.yml
Labels: bug

#139 [Fix] 個別ページotherImagesの幅溢れを解消
  src/templates/PostTemplate.scss
Labels: bug

#140 [Add] 5枚以上のその他画像の溢れ表示を追加
  src/templates/PostTemplate.js
  src/templates/PostTemplate.scss
Labels: bug

#145 [FIx] base64プレースホルダ画像の生成を廃止
  src/components/Fluid200.js
  src/components/Fluid700.js
Labels: enhancement
